Master
GTNewHorizons/GTNH-Lanthanides pull request #14
Opened 2022-05-29 04:58 UTC by ArtherCasan

2022-05-29 16:54 UTC, GlodBlock requested changes

2022-05-29 16:54 UTC, GlodBlock commented on build.gradle
> +    */
remove the comment

2022-05-29 16:56 UTC, ArtherCasan commented on build.gradle
> +    */
I will do it tomorrow

2022-05-30 02:15 UTC, GlodBlock approved these changes

2022-05-30 07:06 UTC, merged