redo "Make Lanth Line Better (mainly Samarium)"
GTNewHorizons/GTNH-Lanthanides pull request #70
Opened 2023-09-29 07:37 UTC by Nxer

2023-09-29 07:55 UTC, boubou19 requested changes

2023-09-29 07:55 UTC, boubou19 commented on src/main/java/com/elisis/gtnhlanth/loader/RecipeLoader.java
> +                .fluidOutputs(LanthanumChlorideConcentrate.getFluidOrGas(3000)).specialValue(800).eut(122880)
use TierEU.RECIPE_ZPM

2023-09-29 07:55 UTC, boubou19 commented on src/main/java/com/elisis/gtnhlanth/loader/RecipeLoader.java
>                  .duration(40).addTo(RecipeAdder.instance.DigesterRecipes);
decompose the tick duration in a unique h/min/s/t way, using the TICKS, SECONDS, MINUTES, HOURS constants, for instance 40 is 2*SECONDS

2023-09-29 07:59 UTC, boubou19 commented
Also i feel like this PR is not properly done, previous one had a 2k changes, now this one only has 58.

2023-09-29 13:39 UTC, boubou19 approved these changes

2023-09-29 13:41 UTC, Dream-Master commented
@Nxer can you resolve the conflict?

2023-09-29 15:34 UTC, Nxer commented
> @Nxer can you resolve the conflict?

where
I'll check again , now way home.

2023-10-01 21:17 UTC, boubou19 approved these changes

2023-10-01 21:18 UTC, merged